/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicIncomingLeadRouteImport } from './routes/api/public/incoming-lead'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIncomingLeadRoute = ApiPublicIncomingLeadRouteImport.update({
  id: '/api/public/incoming-lead',
  path: '/api/public/incoming-lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/incoming-lead': typeof ApiPublicIncomingLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/incoming-lead': typeof ApiPublicIncomingLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/public/incoming-lead': typeof ApiPublicIncomingLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/api/public/incoming-lead'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/api/public/incoming-lead'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/dashboard'
    | '/api/public/incoming-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  ApiPublicIncomingLeadRoute: typeof ApiPublicIncomingLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/incoming-lead': {
      id: '/api/public/incoming-lead'
      path: '/api/public/incoming-lead'
      fullPath: '/api/public/incoming-lead'
      preLoaderRoute: typeof ApiPublicIncomingLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  ApiPublicIncomingLeadRoute: ApiPublicIncomingLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
